{
 "title": "Dash2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (rate(node_cpu_seconds_total{mode=\"system\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPULA",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1" },
    { "expr": "node_load5" },
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "Memory Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  },
  {
   "title": "Место на файловой системе",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes/(1024*1024*1024)"
    }
   ]
  }
 ]
}